### ISSUE TITLE
develop -> master ?

### ISSUE THREAD

**Issue by ibaned** [kokkos/nvcc_wrapper#6]
Is there a policy for when and how changes are accepted from develop into master, and subsequently into Kokkos and Trilinos ? Currently `master` dates to June and my PR to `develop` was merged in August.

**Comment by crtrott** [comment]
Oh sorry. I actually forgot to merge into master her. Your pull request made it all the way to Trilinos already. The general idea is that develop changes here get put into kokkos::develop. And we promote here to master when kokkos promotes to master, so that the master version of nvcc_wrapper is what you see in the master version of Kokkos. I just forgot to do the merge here.
